name: GrotesQ Deployment
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Deploy
    runs-on: Ubuntu-20.04

    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies and build the app
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: NPM Install
        run: npm install
      - name: Next.js Build
        run: npm run build
      - name: Deploy Production
        env:
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        uses: apex/actions/up@v0.5.0
        with:
          args: deploy production --no-build
      - name: Deploy Root
        env:
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        uses: apex/actions/up@v0.5.0
        with:
          args: deploy root --no-build
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: official-website
          SLACK_MESSAGE: 'https://grotesq.com'
          SLACK_TITLE: '배포 완료'
          SLACK_USERNAME: Github Action
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
