name: GrotesQ Deployment
on:
  push:
    branches:
      - v3
jobs:
  build:
    name: Deploy
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies and build the app
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - name: NPM Install
        run: yarn
      - name: Next.js Build
        run: yarn build:next
      - name: Deploy
        run: |
          export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
          export AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
          npm run deploy:serverless
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: official-website
          SLACK_MESSAGE: 'https://v3.grotesq.com'
          SLACK_TITLE: 'v3 배포 완료'
          SLACK_USERNAME: Github Action
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
